GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/63417db2d39125a1d8e040de
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld2VzdCB0ZXN0IHVzZXJuYW1lIiwiaWQiOiI2MzQxN2Q1MmQzOTEyNWExZDhlMDQwZGEiLCJpYXQiOjE2NjUyMzYzMjV9.FV4SyBoDZa1yP4ZyfNgI_D4dYfUzTyWn9UJrtzuiqk4

{
    "title": "newest test",
    "author": "newest test",
    "url": "idk"
}


###
DELETE http://localhost:3003/api/blogs/633a8f39b943c2b9c525e58e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzMzgwZGI3ZTI4MDdlZTAwOGM2NmI3YiIsImlhdCI6MTY2NTMzMTM0MH0.3H1FelIo8Lnt9S24XuhamYOc4EHGInndFgn4iIq1eX0

###
PUT http://localhost:3003/api/blogs/633059c99a3ffba73d0c83ba
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 8
}