GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/63417db2d39125a1d8e040de
###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcnNldCIsImlkIjoiNjMzODBjMGFjMmZmODZjYWIyMWI3YjMyIiwiaWF0IjoxNjY1NDEyMTgwfQ.LFAE8zDqZf6VkqMnTjB8Lc5QsZ7LI3Qx78LJk4xKlwA

{
    "title": "newest test",
    "author": "newest test",
    "url": "idk"
}


###
DELETE http://localhost:3003/api/blogs/633a8f39b943c2b9c525e58e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlcnNldCIsImlkIjoiNjMzODBjMGFjMmZmODZjYWIyMWI3YjMyIiwiaWF0IjoxNjY1NDEyMTgwfQ.LFAE8zDqZf6VkqMnTjB8Lc5QsZ7LI3Qx78LJk4xKlwA

###
PUT http://localhost:3003/api/blogs/633059c99a3ffba73d0c83ba
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 8
}