post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "newest test username",
    "password": "newPassword"
}

// use this to get user token


###
post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}