GET http://localhost:3003/api/blogs
// get all blogs

###
GET http://localhost:3003/api/blogs/633059c99a3ffba73d0c83ba
// get blog by id

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "another one",
    "author": "another aouther",
    "url": "idk"
}

###
DELETE http://localhost:3003/api/blogs/633067e82c591642ba9d90c3

###
PUT http://localhost:3003/api/blogs/633059c99a3ffba73d0c83ba
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 8
}

###
get http://localhost:3003/api/users

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "name": "test",
    "password": "test"
}