get http://localhost:3003/api/users

###
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "newest test username",
    "name": "test",
    "password": "newPassword"
}